baseurl: /rq/
exclude: design
permalink: pretty
markdown: redcarpet
pygments: true

navigation:
- text: Home
  url: 
- text: Docs
  url: docs/
  subs:
  - text: Jobs
    url: docs/
  - text: Workers
    url: docs/workers/
  - text: Results
    url: docs/results/
  - text: Monitoring
    url: docs/monitoring/
  - text: Internals
    url: docs/internals/
- text: Contributing
  url: contrib/
