baseurl: /
exclude: design
permalink: pretty
markdown: redcarpet
pygments: true

navigation:
- text: Home
  url: 
- text: Docs
  url: docs/
  subs:
  - text: Queues
    url: docs/
  - text: Workers
    url: docs/workers/
  - text: Results
    url: docs/results/
  - text: Monitoring
    url: docs/monitoring/
  - text: Connections
    url: docs/connections/
  - text: Exceptions
    url: docs/exceptions/
- text: Patterns
  url: patterns/
  subs:
  - text: Heroku
    url: patterns/
  - text: Django
    url: patterns/django/
  - text: Sentry
    url: patterns/sentry/
- text: Contributing
  url: contrib/
  subs:
  - text: Internals
    url: contrib/
  - text: GitHub
    url: contrib/github/
