baseurl: /rq/
exclude: design
permalink: pretty
markdown: redcarpet
pygments: true

navigation:
- text: Home
  url: /rq/
- text: Docs
  url: /rq/docs/
- text: Contributing
  url: /rq/contrib/
- text: Source
  url: http://git.io/rq
